[2021-08-07 13:58:54,132] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: standardized_pipeline.create_standardized_table_parts 2021-08-07T13:50:00+00:00 [queued]>
[2021-08-07 13:58:54,141] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: standardized_pipeline.create_standardized_table_parts 2021-08-07T13:50:00+00:00 [queued]>
[2021-08-07 13:58:54,142] {taskinstance.py:1087} INFO - 
--------------------------------------------------------------------------------
[2021-08-07 13:58:54,143] {taskinstance.py:1088} INFO - Starting attempt 1 of 1
[2021-08-07 13:58:54,143] {taskinstance.py:1089} INFO - 
--------------------------------------------------------------------------------
[2021-08-07 13:58:54,155] {taskinstance.py:1107} INFO - Executing <Task(MySqlOperator): create_standardized_table_parts> on 2021-08-07T13:50:00+00:00
[2021-08-07 13:58:54,163] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'standardized_pipeline', 'create_standardized_table_parts', '2021-08-07T13:50:00+00:00', '--job-id', '16', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/standardized_pipeline.py', '--cfg-path', '/tmp/tmpokvywicg', '--error-file', '/tmp/tmp9iiz1a2v']
[2021-08-07 13:58:54,159] {standard_task_runner.py:52} INFO - Started process 2610 to run task
[2021-08-07 13:58:54,165] {standard_task_runner.py:77} INFO - Job 16: Subtask create_standardized_table_parts
[2021-08-07 13:58:54,208] {logging_mixin.py:104} INFO - Running <TaskInstance: standardized_pipeline.create_standardized_table_parts 2021-08-07T13:50:00+00:00 [running]> on host ab70d6dafbc6
[2021-08-07 13:58:54,253] {taskinstance.py:1302} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=standardized_pipeline
AIRFLOW_CTX_TASK_ID=create_standardized_table_parts
AIRFLOW_CTX_EXECUTION_DATE=2021-08-07T13:50:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-08-07T13:50:00+00:00
[2021-08-07 13:58:54,254] {mysql.py:70} INFO - Executing: CREATE TABLE `PART` (
  `PART_KEY` int NOT NULL,
  `PART_NAME` text NOT NULL,
  `PART_MFGR` text NOT NULL,
  `PART_BRAND` text NOT NULL,
  `PART_TYPE` text NOT NULL,
  `PART_SIZE` int NOT NULL,
  `PART_CONTAINER` text NOT NULL,
  `PART_RETAILPRICE` int NOT NULL,
  `PART_COMMENT` text NOT NULL,
  `INGESTION_TIMESTAMP` datetime DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`PART_KEY`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
[2021-08-07 13:58:54,262] {base.py:78} INFO - Using connection to: id: dwh_id. Host: dwh, Port: 3306, Schema: , Login: root, Password: ***, extra: {}
[2021-08-07 13:58:54,272] {dbapi.py:204} INFO - Running statement: CREATE TABLE `PART` (
  `PART_KEY` int NOT NULL,
  `PART_NAME` text NOT NULL,
  `PART_MFGR` text NOT NULL,
  `PART_BRAND` text NOT NULL,
  `PART_TYPE` text NOT NULL,
  `PART_SIZE` int NOT NULL,
  `PART_CONTAINER` text NOT NULL,
  `PART_RETAILPRICE` int NOT NULL,
  `PART_COMMENT` text NOT NULL,
  `INGESTION_TIMESTAMP` datetime DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`PART_KEY`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;, parameters: None
[2021-08-07 13:58:54,273] {taskinstance.py:1501} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1157, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1331, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1361, in _execute_task
    result = task_copy.execute(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/providers/mysql/operators/mysql.py", line 72, in execute
    hook.run(self.sql, autocommit=self.autocommit, parameters=self.parameters)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/hooks/dbapi.py", line 184, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/hooks/dbapi.py", line 208, in _run_command
    cur.execute(sql_statement)
  File "/home/airflow/.local/lib/python3.6/site-packages/MySQLdb/cursors.py", line 206, in execute
    res = self._query(query)
  File "/home/airflow/.local/lib/python3.6/site-packages/MySQLdb/cursors.py", line 319, in _query
    db.query(q)
  File "/home/airflow/.local/lib/python3.6/site-packages/MySQLdb/connections.py", line 259, in query
    _mysql.connection.query(self, query)
MySQLdb._exceptions.OperationalError: (1046, 'No database selected')
[2021-08-07 13:58:54,275] {taskinstance.py:1551} INFO - Marking task as FAILED. dag_id=standardized_pipeline, task_id=create_standardized_table_parts, execution_date=20210807T135000, start_date=20210807T135854, end_date=20210807T135854
[2021-08-07 13:58:54,300] {local_task_job.py:149} INFO - Task exited with return code 1
