[2021-08-07 16:36:20,827] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: presentation_pipeline.presentation_customer 2021-08-07T16:30:00+00:00 [queued]>
[2021-08-07 16:36:20,854] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: presentation_pipeline.presentation_customer 2021-08-07T16:30:00+00:00 [queued]>
[2021-08-07 16:36:20,855] {taskinstance.py:1087} INFO - 
--------------------------------------------------------------------------------
[2021-08-07 16:36:20,857] {taskinstance.py:1088} INFO - Starting attempt 1 of 1
[2021-08-07 16:36:20,858] {taskinstance.py:1089} INFO - 
--------------------------------------------------------------------------------
[2021-08-07 16:36:20,872] {taskinstance.py:1107} INFO - Executing <Task(MySqlOperator): presentation_customer> on 2021-08-07T16:30:00+00:00
[2021-08-07 16:36:20,888] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'presentation_pipeline', 'presentation_customer', '2021-08-07T16:30:00+00:00', '--job-id', '44', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/presentation_pipeline.py', '--cfg-path', '/tmp/tmp25vp73i4', '--error-file', '/tmp/tmpp6nsqx6c']
[2021-08-07 16:36:20,880] {standard_task_runner.py:52} INFO - Started process 448 to run task
[2021-08-07 16:36:20,891] {standard_task_runner.py:77} INFO - Job 44: Subtask presentation_customer
[2021-08-07 16:36:20,964] {logging_mixin.py:104} INFO - Running <TaskInstance: presentation_pipeline.presentation_customer 2021-08-07T16:30:00+00:00 [running]> on host c8552014663a
[2021-08-07 16:36:21,059] {taskinstance.py:1302} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=presentation_pipeline
AIRFLOW_CTX_TASK_ID=presentation_customer
AIRFLOW_CTX_EXECUTION_DATE=2021-08-07T16:30:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-08-07T16:30:00+00:00
[2021-08-07 16:36:21,061] {mysql.py:70} INFO - Executing: INSERT IGNORE INTO presentation.NATION (
	`CUSTOMER_KEY`,
    `NATION_NAME`,
    `CUSTOMER_ACCTBAL`,
    `CUSTOMER_MKTSEGMENT`
) 

SELECT 
	c.CUSTOMER_KEY,
	n.NATION_NAME,
	c.CUSTOMER_ACCTBAL,
	c.CUSTOMER_MKTSEGMENT
FROM 
	standardized.CUSTOMER c 
LEFT JOIN
	standardized.NATION n 
	ON c.NATION_KEY = n.NATION_KEY 
WHERE
	c.INGESTION_TIMESTAMP >= DATE_SUB(NOW(), INTERVAL 5 MINUTE)
[2021-08-07 16:36:21,085] {base.py:78} INFO - Using connection to: id: dwh_id. Host: dwh, Port: 3306, Schema: , Login: root, Password: ***, extra: {}
[2021-08-07 16:36:21,102] {dbapi.py:204} INFO - Running statement: INSERT IGNORE INTO presentation.NATION (
	`CUSTOMER_KEY`,
    `NATION_NAME`,
    `CUSTOMER_ACCTBAL`,
    `CUSTOMER_MKTSEGMENT`
) 

SELECT 
	c.CUSTOMER_KEY,
	n.NATION_NAME,
	c.CUSTOMER_ACCTBAL,
	c.CUSTOMER_MKTSEGMENT
FROM 
	standardized.CUSTOMER c 
LEFT JOIN
	standardized.NATION n 
	ON c.NATION_KEY = n.NATION_KEY 
WHERE
	c.INGESTION_TIMESTAMP >= DATE_SUB(NOW(), INTERVAL 5 MINUTE), parameters: None
[2021-08-07 16:36:21,104] {taskinstance.py:1501} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1157, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1331, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1361, in _execute_task
    result = task_copy.execute(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/providers/mysql/operators/mysql.py", line 72, in execute
    hook.run(self.sql, autocommit=self.autocommit, parameters=self.parameters)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/hooks/dbapi.py", line 184, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/hooks/dbapi.py", line 208, in _run_command
    cur.execute(sql_statement)
  File "/home/airflow/.local/lib/python3.6/site-packages/MySQLdb/cursors.py", line 206, in execute
    res = self._query(query)
  File "/home/airflow/.local/lib/python3.6/site-packages/MySQLdb/cursors.py", line 319, in _query
    db.query(q)
  File "/home/airflow/.local/lib/python3.6/site-packages/MySQLdb/connections.py", line 259, in query
    _mysql.connection.query(self, query)
MySQLdb._exceptions.OperationalError: (1054, "Unknown column 'CUSTOMER_KEY' in 'field list'")
[2021-08-07 16:36:21,111] {taskinstance.py:1551} INFO - Marking task as FAILED. dag_id=presentation_pipeline, task_id=presentation_customer, execution_date=20210807T163000, start_date=20210807T163620, end_date=20210807T163621
[2021-08-07 16:36:21,199] {local_task_job.py:149} INFO - Task exited with return code 1
