[2021-08-07 15:10:44,845] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: standardized_pipeline.create_standardized_table_supplier 2021-08-07T15:05:00+00:00 [queued]>
[2021-08-07 15:10:44,881] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: standardized_pipeline.create_standardized_table_supplier 2021-08-07T15:05:00+00:00 [queued]>
[2021-08-07 15:10:44,882] {taskinstance.py:1087} INFO - 
--------------------------------------------------------------------------------
[2021-08-07 15:10:44,883] {taskinstance.py:1088} INFO - Starting attempt 1 of 1
[2021-08-07 15:10:44,884] {taskinstance.py:1089} INFO - 
--------------------------------------------------------------------------------
[2021-08-07 15:10:44,928] {taskinstance.py:1107} INFO - Executing <Task(MySqlOperator): create_standardized_table_supplier> on 2021-08-07T15:05:00+00:00
[2021-08-07 15:10:44,936] {standard_task_runner.py:52} INFO - Started process 94 to run task
[2021-08-07 15:10:44,961] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'standardized_pipeline', 'create_standardized_table_supplier', '2021-08-07T15:05:00+00:00', '--job-id', '3', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/standardized_pipeline.py', '--cfg-path', '/tmp/tmp6e7b5hp2', '--error-file', '/tmp/tmp_beubrte']
[2021-08-07 15:10:44,964] {standard_task_runner.py:77} INFO - Job 3: Subtask create_standardized_table_supplier
[2021-08-07 15:10:45,116] {logging_mixin.py:104} INFO - Running <TaskInstance: standardized_pipeline.create_standardized_table_supplier 2021-08-07T15:05:00+00:00 [running]> on host 840edc4bbc5d
[2021-08-07 15:10:45,243] {taskinstance.py:1302} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=standardized_pipeline
AIRFLOW_CTX_TASK_ID=create_standardized_table_supplier
AIRFLOW_CTX_EXECUTION_DATE=2021-08-07T15:05:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-08-07T15:05:00+00:00
[2021-08-07 15:10:45,246] {mysql.py:70} INFO - Executing: CREATE TABLE IF NOT EXISTS standardized.SUPPLIER (
  `SUPPLIER_KEY` int NOT NULL,
  `SUPPLIER_NAME` text NOT NULL,
  `SUPPLIER_ADDRESS` text NOT NULL,
  `NATION_KEY` int NOT NULL,
  `SUPPLIER_PHONE` text NOT NULL,
  `SUPPLIER_ACCTBAL` int NOT NULL,
  `SUPPLIER_COMMENT` text NOT NULL,
  `INGESTION_TIMESTAMP` datetime DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
[2021-08-07 15:10:45,294] {taskinstance.py:1501} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1157, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1331, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1361, in _execute_task
    result = task_copy.execute(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/providers/mysql/operators/mysql.py", line 72, in execute
    hook.run(self.sql, autocommit=self.autocommit, parameters=self.parameters)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/hooks/dbapi.py", line 177, in run
    with closing(self.get_conn()) as conn:
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/providers/mysql/hooks/mysql.py", line 164, in get_conn
    getattr(self, self.conn_name_attr)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/hooks/base.py", line 67, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/connection.py", line 379, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `dwh_id` isn't defined
[2021-08-07 15:10:45,309] {taskinstance.py:1551} INFO - Marking task as FAILED. dag_id=standardized_pipeline, task_id=create_standardized_table_supplier, execution_date=20210807T150500, start_date=20210807T151044, end_date=20210807T151045
[2021-08-07 15:10:45,408] {local_task_job.py:149} INFO - Task exited with return code 1
