[2021-08-07 09:28:57,099] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: to_datalake_pipeline.extract_from_git 2021-08-07T09:28:56.234948+00:00 [queued]>
[2021-08-07 09:28:57,113] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: to_datalake_pipeline.extract_from_git 2021-08-07T09:28:56.234948+00:00 [queued]>
[2021-08-07 09:28:57,114] {taskinstance.py:1087} INFO - 
--------------------------------------------------------------------------------
[2021-08-07 09:28:57,115] {taskinstance.py:1088} INFO - Starting attempt 1 of 1
[2021-08-07 09:28:57,116] {taskinstance.py:1089} INFO - 
--------------------------------------------------------------------------------
[2021-08-07 09:28:57,131] {taskinstance.py:1107} INFO - Executing <Task(PythonOperator): extract_from_git> on 2021-08-07T09:28:56.234948+00:00
[2021-08-07 09:28:57,137] {standard_task_runner.py:52} INFO - Started process 331 to run task
[2021-08-07 09:28:57,142] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'to_datalake_pipeline', 'extract_from_git', '2021-08-07T09:28:56.234948+00:00', '--job-id', '3', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/to_datalake_pipeline.py', '--cfg-path', '/tmp/tmpk49kpuf1', '--error-file', '/tmp/tmpaafy09b9']
[2021-08-07 09:28:57,143] {standard_task_runner.py:77} INFO - Job 3: Subtask extract_from_git
[2021-08-07 09:28:57,198] {logging_mixin.py:104} INFO - Running <TaskInstance: to_datalake_pipeline.extract_from_git 2021-08-07T09:28:56.234948+00:00 [running]> on host 4446dd23665f
[2021-08-07 09:28:57,260] {taskinstance.py:1302} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=to_datalake_pipeline
AIRFLOW_CTX_TASK_ID=extract_from_git
AIRFLOW_CTX_EXECUTION_DATE=2021-08-07T09:28:56.234948+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-08-07T09:28:56.234948+00:00
[2021-08-07 09:28:57,261] {logging_mixin.py:104} INFO - Downloading data from -> https://raw.githubusercontent.com/rezaprimasatya/DTO-DE-JUN-MID/main/data.zip
[2021-08-07 09:28:58,065] {logging_mixin.py:104} INFO - Unzipping Data
[2021-08-07 09:28:58,135] {logging_mixin.py:104} INFO - Transform Data to Pandas Dataframe
[2021-08-07 09:28:58,293] {logging_mixin.py:104} INFO - Load data to datalake
[2021-08-07 09:28:58,303] {logging_mixin.py:104} INFO - Pipeline Error-> 'Variable DWH_USER does not exist'
[2021-08-07 09:28:58,312] {python.py:151} INFO - Done. Returned value was: None
[2021-08-07 09:28:58,322] {taskinstance.py:1211} INFO - Marking task as SUCCESS. dag_id=to_datalake_pipeline, task_id=extract_from_git, execution_date=20210807T092856, start_date=20210807T092857, end_date=20210807T092858
[2021-08-07 09:28:58,344] {taskinstance.py:1265} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2021-08-07 09:28:58,363] {local_task_job.py:149} INFO - Task exited with return code 0
